### ISSUE TITLE
Providing Profile to Chrome and camera permission issue

### ISSUE THREAD

**Issue by ImranTelebu** [webrtc/KITE#110]
Steps : 1. When I run Chrome Browser from Kite and use Fake Media, it will open on temporary profile that has default settings ,which wont permit  camera access by default , it prevent from subscribing to SFU serve. 
for that I am using profile parameter in kite but it always choose temporary profile. 
so can you help me to open chrome browser on custom supplied profile.
![kite](https://user-images.githubusercontent.com/51738071/79120197-f3210e00-7daf-11ea-9c09-72506ad42c25.PNG)
![config](https://user-images.githubusercontent.com/51738071/79120200-f9af8580-7daf-11ea-9244-79e49ded7022.PNG)
![automated chrome](https://user-images.githubusercontent.com/51738071/79120432-85291680-7db0-11ea-9e68-72209a3a636e.PNG)

**Comment by namvuCosmo** [comment]
Hi,

For the moment the `profile` is not a parameter for the client object. 

Can you tell me what the extra settings/data you need to include in your custom profile?

**Comment by ImranTelebu** [comment]
whenever I am using actual camera , Automated Browser doesn't ask for camera permission it grant me . but when I use Fake media in place of camera visuals , I don't get the camera permission although media file is playing. So I want it to give me Permission irrespective of the visuals coming from actual camera or fake media file. I need this because without camera permission stream will not subscribe to mcu server.

**Comment by namvuCosmo** [comment]
I see.

If you don't want to use fake media, please use `"useFakeMedia": false` in the client configuration.

However, since this is meant for automated test, we put in the reference to allow permission for camera's audio and video when creating the webdriver. I don't think we will make this configurable.

If you want to have the permission pop up as normal and click on it manually, you'll need to:
 - put useFakeMedia as false
 - comment out lines 316 and 317 in the class [WebDriverFactory](https://github.com/webrtc/KITE/blob/master/KITE-Framework/src/main/java/org/webrtc/kite/WebDriverFactory.java), and recompile the Engine.

![image](https://user-images.githubusercontent.com/27989546/79216831-6c883180-7e80-11ea-9dc2-38d7b6bf4958.png)

**Comment by ImranTelebu** [comment]
Actually I am doing automation for load testing , for that to achieve more load I have to use Fake media , so that I can open multiple browser instances , If I use camera , I wont be able to open Multiple instances on a single machine .

**Comment by namvuCosmo** [comment]
Well, if you want to use fake media, naturally, it won't ask for permission and grant it automatically.

I'm not sure I can help you with you particular scenario. 

Does it work when you use cam instead of fake media (even though it doesn't ask you for permission)?

If it does, then maybe you can try modifying the code a bit. Same file I mentioned above, but instead of commenting the lines, you take that out of the else loop. I'm thinking maybe it still uses fake media, but also has the permission in place. Like this:
![image](https://user-images.githubusercontent.com/27989546/79219507-fc2fdf00-7e84-11ea-8177-76506bdb0418.png)

If it still doesn't work, Idk what else to do 🤔 .

I'll keep in mind the chrome profile for future update.

**Comment by ImranTelebu** [comment]
Thank you.
It worked , appreciate your help ,  I spent much time searching for solution, you rectified correctly  , I think its required to have camera permission for Fake media, so If kite comes with the change by default would also be helpful.
