### ISSUE TITLE
How can I achieve Mobile Emulation mode using Kite ?

### ISSUE THREAD

**Issue by kavyasetty456** [webrtc/KITE#124]
Hi,

Could you please suggest me how can I achieve Mobile Emulation mode using Kite? I already tried in multiple ways but it seems no use and there is no inbuilt method in Kite for using Mobile Emulation mode.

Please find the below screenshot for your reference

![MobileEmulation](https://user-images.githubusercontent.com/54302175/82045911-890cc900-96cd-11ea-85c4-365f68156e22.PNG)

Thank You,
Kavya Setty.

**Comment by namvuCosmo** [comment]
Hi,

We haven't implemented this because there hasn't been need for it.

However I just tried the example here : https://chromedriver.chromium.org/mobile-emulation

![image](https://user-images.githubusercontent.com/27989546/82046947-8073bd00-96e4-11ea-9093-fba5bc53146f.png)

Is this the result you want?

![image](https://user-images.githubusercontent.com/27989546/82046899-6639df00-96e4-11ea-8519-12394384fff2.png)

**Comment by kavyasetty456** [comment]
Hi,

I used the same code which you have used but still browser is opening in normal way.

you are keeping the code in WebDriverFactory.java only?

**Comment by namvuCosmo** [comment]
Those were the only 3 lines I added. 

I'm not sure if it changes anything, but I tested it only with chrome canary (v. 84).

**Comment by kavyasetty456** [comment]
Even I also used the same code in WebDriverFactory.java but still for me it is not changing into mobile emulation mode.
And I am testing in Chrome Browser  81.0.4044.138  version.

**Comment by namvuCosmo** [comment]
I have the same result with chrome 81
![image](https://user-images.githubusercontent.com/27989546/82051461-7b1a7080-96ec-11ea-9e21-04dd25617a4a.png)


Are you using only the 3 new lines I added?

**Comment by kavyasetty456** [comment]
Now its working for me too. Yeah I am using the same code only.

I updated Kite and kept those 3 lines and its working for me

Thank You for your support!!

**Comment by namvuCosmo** [comment]
Np :)
