### ISSUE TITLE
KITE limitations?

### ISSUE THREAD

**Issue by JuanJEA** [webrtc/KITE#152]
Are there any limitations to running tests in this version of KITE?
I am trying to run 5 Janus conference rooms.
This is the way I do it: I open 5 terminals and navigate to /opt/KITE/KITE-Sample-Tests/KITE-Janus-Test then inside the directory and in each terminal I executed the following lines
"r configs / test1.json"
"r configs / test2.json"
"r configs / test3.json"
"r configs / test4.json"
"r configs / test5.json"

Each room has 15 members, but when executing the third line it generates an error (attached file) and I still don't know what causes it.

Could you please help me.
[r.txt](https://github.com/webrtc/KITE/files/5093926/r.txt)

**Comment by namvuCosmo** [comment]
Hi,

Did the first 2 lines get executed correctly?

Which chrome version are you using? The issue is coming from chromewebdriver rather than KITE itself. Are you running Chrome in headless mode?

Can you please also attach your test config file.

**Comment by JuanJEA** [comment]
Hi.

Yes, the first 2 lines run ok.
Chrome version: 84.0.4147.125
Are you running Chrome in headless mode? No.

My configs files.
[Kite_VideoRoom.zip](https://github.com/webrtc/KITE/files/5103576/Kite_VideoRoom.zip)

Thank you.

Note: I send each test to a different room because I have not yet understood how to use the usersPerRoom parameter.

**Comment by namvuCosmo** [comment]
For the usersPerRoom, you can take a look at https://github.com/webrtc/KITE/issues/140

Are you running all these Chrome on your pc, or you have a grid of multiple Chrome nodes?

The error from chromedriver is because the Chrome was not able to be launched. One machine might not be able to handle that many instances of Chrome. Depend on your hardware, I would recommend keeping the number of Chrome instances per Selenium Node (machine) under 20 (there is also a limit on how many video streams a machine can handle later in the test)

The config files seem normal, I think if you keep the tuple size lower then you can run more tests with different config files.

After each test, sometimes chromedriver can have the tendency to keep running in the background. You can also check for the "chromedriver" (or chromedriver.exe) process and kill them.

**Comment by namvuCosmo** [comment]
Closed due to inactivity.
